name: crack_tech_app
version: 1.0.0+1
publish_to: none
description: A interview task Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_launcher_icons: ^0.11.0
  dio: ^4.0.6
  cached_network_image: ^3.2.1 #network image
  hive: ^2.2.3
  path_provider: ^2.0.15
  connectivity_plus: ^2.3.7

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-logo.jpeg"

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/loader/

