name: crack_tech_app
version: 1.0.0+1
publish_to: none
description: A interview task Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2 #cupertino icon
  get: 4.6.5 #state management
  flutter_launcher_icons: ^0.11.0 #Icons
  dio: ^4.0.6 #Data fetch
  cached_network_image: ^3.2.1 #network image
  hive: ^2.2.3 #Cash data
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15 #path
  connectivity_plus: ^2.3.7 #network

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  test: ^1.16.8
  mockito: ^5.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-logo.jpeg"

flutter: 
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf

  assets:
    - assets/icons/
    - assets/loader/

